function [obstacles, waypoints, waypoint_traj_indices, ...
          x_trajectory, u_trajectory, y_trajectory] = parload(trajectory_file)
    load(trajectory_file, ...
        'obstacles', 'waypoints', 'waypoint_traj_indices', ...
        'x_trajectory', 'u_trajectory', 'y_trajectory');
end